### ISSUE TITLE
How to I connect the Magic Home Controller to my WiFi Network 

### ISSUE THREAD

**Issue by PasiB** [sahilchaddha/homebridge-magichome-platform#16]
Hey sahilchaddha!
I bought the Magic Home Controller and I want to use your plugin to control it with home.
How do I get the IP of the LED controller. If I connect the controller to power adapter, it creates it's own network. I can control the strip via the Magic Home app but only if I connect to the created wlan network. So how can I connect the controller to my own wlan network and therefore get a IP adress for the plugin? Do I have to flash the controller? I can't find any information about it in your description. I'm looking forward to your answer :-)

**Comment by PasiB** [comment]
Changed title mistake

**Comment by iwonder-1618** [comment]
Hey @PasiB ,
You will need to use MagicHome App first to connect your lights to your Wifi Network. Once connected, your light will be assigned an IP address. You can use IP Address in the plugin config.json.
You can refer to https://www.youtube.com/watch?v=ZI-D_xVxTHM for guide.

**Comment by PasiB** [comment]
Sorry, my fault! I was setting up too fast, now I easily connected it to my own Wi-Fi in the Magic Home app. I also installed the plugin and it worked immediately and it took only around 5 minutes setting it up. That you for the great work and the easy setup without flashing oder something. Nice 👌🏼👌🏼👌🏼
