### ISSUE TITLE
Log entries

### ISSUE THREAD

**Issue by monza258** [sahilchaddha/homebridge-magichome-platform#4]
Can the log entries be reduced? The log file writes a change every second.

`ov 17 22:17:37 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:37] [homebridge-magichome-platform.MagicHome-Platform] Discovering Devices
Nov 17 22:17:37 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:37] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] 2 bulbs found
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: 6001948C9575=192.168.0.46
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: 60019495601D=192.168.0.68
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] Saving Lights
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] {"6001948C9575":"192.168.0.46","192.168.0.46":"192.168.0.46","60019495601D":"192.168.0.68","192.168.0.68":"192.168.0.68"}
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] Lights Saved.
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] Discovery Finished
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [homebridge-magichome-platform.MagicHome-Platform] { '6001948C9575': '192.168.0.46',
Nov 17 22:17:41 raspberrypi2 homebridge[18462]:   '192.168.0.46': '192.168.0.46',
Nov 17 22:17:41 raspberrypi2 homebridge[18462]:   '60019495601D': '192.168.0.68',
Nov 17 22:17:41 raspberrypi2 homebridge[18462]:   '192.168.0.68': '192.168.0.68' }
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.46 -i
Nov 17 22:17:41 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:41] [MagicHome-Platform] Unknown ID [192.168.0.46] ON  [Color: (22, 12, 47)]
Nov 17 22:17:42 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:42] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.68 -i
Nov 17 22:17:42 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:42] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
Nov 17 22:17:47 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:47] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.68 -i
Nov 17 22:17:47 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:47] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
Nov 17 22:17:51 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:51] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.46 -i
Nov 17 22:17:51 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:51] [MagicHome-Platform] Unknown ID [192.168.0.46] ON  [Color: (22, 12, 47)]
Nov 17 22:17:52 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:52] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.68 -i
Nov 17 22:17:52 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:52] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
Nov 17 22:17:56 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:56] [homebridge-magichome-platform.MagicHome-Platform] Discovering Devices
Nov 17 22:17:57 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:57] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.68 -i
Nov 17 22:17:57 raspberrypi2 homebridge[18462]: [2018-11-17 22:17:57] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] 2 bulbs found
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: 6001948C9575=192.168.0.46
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: 60019495601D=192.168.0.68
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] Saving Lights
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] {"6001948C9575":"192.168.0.46","192.168.0.46":"192.168.0.46","60019495601D":"192.168.0.68","192.168.0.68":"192.168.0.68"}
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] Lights Saved.
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] Discovery Finished
Nov 17 22:18:00 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:00] [homebridge-magichome-platform.MagicHome-Platform] { '6001948C9575': '192.168.0.46',
Nov 17 22:18:00 raspberrypi2 homebridge[18462]:   '192.168.0.46': '192.168.0.46',
Nov 17 22:18:00 raspberrypi2 homebridge[18462]:   '60019495601D': '192.168.0.68',
Nov 17 22:18:00 raspberrypi2 homebridge[18462]:   '192.168.0.68': '192.168.0.68' }
Nov 17 22:18:01 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:01] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.46 -i
Nov 17 22:18:01 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:01] [MagicHome-Platform] Unknown ID [192.168.0.46] ON  [Color: (22, 12, 47)]
Nov 17 22:18:02 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:02] [MagicHome-Platform] /usr/local/lib/node_modules/homebridge-magichome-platform/src/flux_led.py 192.168.0.68 -i
Nov 17 22:18:02 raspberrypi2 homebridge[18462]: [2018-11-17 22:18:02] [MagicHome-Platform] Unknown ID [192.168.0.68] OFF [Color: (22, 12, 47)]
`

**Comment by sahilchaddha** [comment]
Hi you can disable printing additional logs from homebridge's config.json.
Kindly set `debug` as `false`. You can refer to config-sample.json.
We will be cleaning up logs in future release of the plugin.

**Comment by monza258** [comment]
Thank you. It works
