### ISSUE TITLE
Cant Install

### ISSUE THREAD

**Issue by EvilShark25** [sahilchaddha/homebridge-magichome-platform#5]
Hey I tried to install this plugin on my banana pi.
But I always get this error:

___________________________________________________________________________________________________________
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-magichome-platform/node_modules/node-persist/node_modules/mkdirp/bin'
npm ERR! error rolling back  homebridge-magichome-platform@1.2.5 { Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/homebridge-magichome-platform/node_modules/node-persist/node_modules/mkdirp/bin'
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/homebridge-magichome-platform/node_modules/node-persist/node_modules/mkdirp/bin' }
npm ERR! Error: Method Not Allowed
npm ERR!     at errorResponse (/usr/share/npm/lib/cache/add-named.js:260:10)
npm ERR!     at /usr/share/npm/lib/cache/add-named.js:120:12
npm ERR!     at saved (/usr/share/npm/node_modules/npm-registry-client/lib/get.js:167:7)
npm ERR!     at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.4.112-sun7i
npm ERR! command "/usr/bin/node" "/usr/bin/npm" "install" "-g" "--unsafe-perm" "homebridge-magichome-platform"
npm ERR! cwd /root/.homebridge
npm ERR! node -v v8.11.1
npm ERR! npm -v 1.4.21
npm ERR! code E405
npm ERR! tar.unpack untar error /root/.npm/mkdirp/0.5.1/package.tgz
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     /root/.homebridge/npm-debug.log
npm ERR! not ok code 0

__________________________________________________________________________________________________________

Any idea to fix that?

**Comment by sahilchaddha** [comment]
Hey @EvilShark25, Try updating your node & npm to latest version.
Also try uninstalling the plugin forcefully by running `rm -rf /usr/local/lib/node_modules/homebridge-magichome-platform` before reinstalling the plugin.

**Comment by EvilShark25** [comment]
The last one fixed it thank you!
