### ISSUE TITLE
rgb support

### ISSUE THREAD

**Issue by krobipd** [sahilchaddha/homebridge-magichome-platform#7]
hello

i discovered that I only can control me leds with your plugin when "setup=rgbww".
but I only have rgb, so in the magic home app I only choose rgb nothing else.

its not really a bug but would be great to reflect the real config.
they work with rgbww - in the magic home app they also work with rgb, rgbw and rgbww.
but its not necessary to add all this extra option when the leds/control do not need this.

**Comment by AnanyaKirti** [comment]
hey, 
I have an RGBW strip, and I would like the ability to change the white led's intensity apart from the regular rgb.
Thanks!

**Comment by sahilchaddha** [comment]
Try setting `pureWhite` to true. I am assuming that your light has independent power supply for White LEDs.
