### ISSUE TITLE
disable discovery

### ISSUE THREAD

**Issue by ageorgios** [sahilchaddha/homebridge-magichome-platform#8]
Is there an option to disable discovery to avoid unnecessary wifi traffic?

**Comment by sahilchaddha** [comment]
Hey @ageorgios ,

Thanks for your suggestion. I have updated the plugin to `1.2.6` with an option to disable discovery.

```
{
    "platforms": [
        {
            "platform": "MagicHome-Platform",
            "debug": true,
            "disableDiscovery": true,
            "lights": [
                {
              {...}
```

Note : Disabling discovery will not be able to find lights based on MAC Address. Only IPs

**Comment by ageorgios** [comment]
thank you very much!

**Comment by ageorgios** [comment]
Understood.
On your next code update please consider option like setting timeout=0 to disable the updateStatus action for those that only use homekit for color changes.

Thank you.

**Comment by sahilchaddha** [comment]
Hey @ageorgios , The plugin is updated to version `1.4.0`. You can set timeout to `0` to disable polling of lights.

**Comment by ageorgios** [comment]
great! thanx!
